// PHANTOM Core - PRD Generator
import { getContextEngine } from './context.js';

export interface PRDSection {
  title: string;
  content: string;
}

export interface PRD {
  id: string;
  title: string;
  version: string;
  status: 'draft' | 'review' | 'approved' | 'archived';
  createdAt: string;
  updatedAt: string;
  sections: PRDSection[];
}

export function generatePRD(title: string): PRD {
  const id = `prd_${Date.now().toString(36)}`;
  const now = new Date().toISOString();

  const sections: PRDSection[] = [
    {
      title: 'Overview',
      content: `## ${title}\n\nThis PRD outlines the requirements for ${title}. It covers the problem statement, proposed solution, user stories, technical requirements, and success metrics.`,
    },
    {
      title: 'Problem Statement',
      content: `### Problem\n\nUsers currently face challenges with the existing workflow. This feature addresses the core pain point by providing a streamlined solution.\n\n### Impact\n- User satisfaction improvement: estimated +15%\n- Support ticket reduction: estimated -20%\n- Workflow efficiency gain: estimated +30%`,
    },
    {
      title: 'Proposed Solution',
      content: `### Solution Overview\n\nImplement ${title} with the following key capabilities:\n\n1. **Core Functionality** — Primary feature implementation\n2. **User Interface** — Intuitive UI following existing design patterns\n3. **Integration Points** — Seamless connection with existing systems\n4. **Data Model** — Efficient storage and retrieval`,
    },
    {
      title: 'User Stories',
      content: `### User Stories\n\n**US-1:** As a user, I want to ${title.toLowerCase()} so that I can improve my workflow.\n- Acceptance Criteria:\n  - [ ] Feature is accessible from the main navigation\n  - [ ] Action completes within 2 seconds\n  - [ ] Success/error feedback is displayed\n  - [ ] State is persisted across sessions\n\n**US-2:** As an admin, I want to configure ${title.toLowerCase()} settings so that I can customize the experience.\n- Acceptance Criteria:\n  - [ ] Settings are accessible from the admin panel\n  - [ ] Changes take effect immediately\n  - [ ] Default values are sensible`,
    },
    {
      title: 'Technical Requirements',
      content: `### Technical Requirements\n\n**Architecture:**\n- RESTful API endpoints for CRUD operations\n- Database schema migration required\n- Cache layer for frequently accessed data\n\n**Performance:**\n- Page load: < 2s (P95)\n- API response: < 500ms (P95)\n- Database queries: < 100ms\n\n**Security:**\n- Authentication required for all endpoints\n- Role-based access control\n- Input validation and sanitization\n- Rate limiting on public endpoints`,
    },
    {
      title: 'Success Metrics',
      content: `### Success Metrics\n\n| Metric | Current | Target | Measurement |\n|--------|---------|--------|-------------|\n| Adoption Rate | 0% | 60% in 30 days | Analytics |\n| User Satisfaction | N/A | 4.0+ / 5.0 | Survey |\n| Task Completion | N/A | 85% | Analytics |\n| Support Tickets | Baseline | -20% | Support data |`,
    },
    {
      title: 'Timeline',
      content: `### Timeline\n\n- **Week 1-2:** Design + Technical Spec\n- **Week 3-4:** Core Implementation\n- **Week 5:** Testing + QA\n- **Week 6:** Beta Launch (10% rollout)\n- **Week 7:** Full Launch\n- **Week 8:** Post-launch monitoring`,
    },
    {
      title: 'Risks & Mitigations',
      content: `### Risks\n\n| Risk | Probability | Impact | Mitigation |\n|------|-------------|--------|------------|\n| Scope creep | Medium | High | Strict PRD adherence |\n| Technical complexity | Low | Medium | Spike in Sprint 1 |\n| User adoption | Medium | High | In-app onboarding |\n| Performance impact | Low | High | Load testing |\n\n### Open Questions\n1. Integration priority with third-party services?\n2. Rollout strategy for existing users?\n3. Data migration requirements?`,
    },
  ];

  return {
    id,
    title,
    version: '1.0',
    status: 'draft',
    createdAt: now,
    updatedAt: now,
    sections,
  };
}

export function prdToMarkdown(prd: PRD): string {
  const lines: string[] = [
    `# PRD: ${prd.title}`,
    '',
    `**ID:** ${prd.id}`,
    `**Version:** ${prd.version}`,
    `**Status:** ${prd.status}`,
    `**Created:** ${prd.createdAt}`,
    `**Updated:** ${prd.updatedAt}`,
    '',
    '---',
    '',
  ];

  for (const section of prd.sections) {
    lines.push(section.content);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('');
  lines.push('*Generated by PHANTOM — The invisible force behind every great product.*');

  return lines.join('\n');
}
